# Generated by Django 2.0.7 on 2019-03-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gunit',
            field=models.CharField(default='带盆载好', max_length=20, verbose_name='商品单位'),
        ),
    ]
