# Generated by Django 2.0.7 on 2019-03-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartinfo',
            options={'verbose_name': '购物车商品信息', 'verbose_name_plural': '购物车商品信息'},
        ),
    ]
