# Generated by Django 2.0.7 on 2019-03-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0002_auto_20190306_1409'),
        ('df_goods', '0002_auto_20190328_2054'),
        ('df_cart', '0002_auto_20190306_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_count', models.IntegerField(default=0)),
                ('o_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo')),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单商品信息',
            },
        ),
    ]
